on:
  push:
  schedule:
    - cron:  '21 1 * * FRI'

name: Continuous integration

jobs:
  primary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
        continue-on-error: true # Currently not clean

  secondary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - beta
          - nightly
          - 1.31.0

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: update

      # This is the version last compatible with 1.31
      - uses: actions-rs/cargo@v1
        with:
          command: update
          args: -p backtrace --precise 0.3.35
        if: matrix.rust == '1.31.0'

      - uses: actions-rs/cargo@v1
        with:
          command: build

      # It's not worth making the tests run on 1.31 -- building the
      # code is enough.
      - uses: actions-rs/cargo@v1
        with:
          command: test
        if: matrix.rust != '1.31.0'

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: test
